<?php
/** Copyright 2012 Hochschule Luzern - Technik & Architektur
 *
 * Provides access to the TIP guestbook table in the MySQL database.
 * Supports listing of all guestbok items, inserting new items and removing
 * an exiting item.
 * @author Peter Sollberger <peter.sollberger@hslu.ch>
 */
class GuestbookAccess
{
    private $db;

    /**
     * Opens the database.
     */
    public function __construct()
    {
        $username = "root";   //tipuser
        $password = "";       //tiptop
        $database = "tip";

        // Open the database
        $this->db = mysql_connect("localhost", $username, $password);
        if ($this->db == false) {
            die("Unable to connect to database");
        }

        // Select database
        mysql_select_db($database);
    }

    /**
     * Closes the database.
     */
    public function __destruct()
    {
        mysql_close($this->db);
    }

    /**
     * Return in an table (two-dimensional array) all entries of the guest book.
     * Each row of the table represents one entry in the guest book.
     * @return table[...]["Index"]   --> Integer: Index of the entry (for deleting)
     *         table[...]["Name"]    --> String: name of the user
     *         table[...]["eMail"]   --> String: e-Mail of the user
     *         table[...]["Comment"] --> String: The guest book entry (as text)
     *         table[...]["Date"]    --> String: Date and time of the entry
     */
    public function getEntries()
    {
        // Make querry
        $result = mysql_query("SELECT * FROM guestbook");

        $table = false;
        $i = 0;
        while ($row = mysql_fetch_array($result)) {
            $table[$i]["Index"]   = $row["indes"];
            $table[$i]["Date"]    = $row["date"];
            $table[$i]["Name"]    = $row["name"];
            $table[$i]["eMail"]   = $row["email"];
            $table[$i]["Comment"] = $row["comment"];
            $i++;
        }

        mysql_free_result($result);

        return $table;
    }

    /**
     * Evaluates current time and adds a new guestbook entry with given name,
     * e-Mail and comment.
     * @param String $name    User name
     * @param String $eMail   User e-mail address
     * @param String $comment The entry text
     * @return On success: Integer Index generated by the database for the entry
     *         On failure: Boolean false
     */
    function addEntry($name, $email, $comment)
    {
        // For security: supress SQL injection
        $name    = mysql_real_escape_string($name);
        $eMail   = mysql_real_escape_string($email);
        $comment = mysql_real_escape_string($comment);

        // Add entry to the database
        $result = mysql_query("INSERT INTO guestbook (name, email, comment) VALUES ('$name', '$eMail', '$comment')");

        if ($result)
        {
            $result = mysql_insert_id();
        }

        return $result;
    }

    /**
     * Return in an lis(one-dimensional array) all data of one guest book entry.
     * @return list["Index"]   --> Integer: Index of the entry (for deleting)
     *         list["Name"]    --> String: name of the user
     *         list["eMail"]   --> String: e-Mail of the user
     *         list["Comment"] --> String: The guest book entry (as text)
     *         list["Date"]    --> String: Date and time of the entry
     */
    public function getEntry($index)
    {
        // For security: supress SQL injection
        settype($index, 'Integer');

        // Make querry
        $result = mysql_query("SELECT * FROM guestbook WHERE indes = '$index'");

        $list = false;
        $row = mysql_fetch_array($result);
        if ($row != false) {
            $list["Index"]   = $row["indes"];
            $list["Date"]    = $row["date"];
            $list["Name"]    = $row["name"];
            $list["eMail"]   = $row["email"];
            $list["Comment"] = $row["comment"];
        }

        mysql_free_result($result);

        return $list;
    }

    /**
     * Removes the entry with the given index from the database.
     * @param Integer $index Index of the entry to remove
     * @return Boolean true on success.
     */
    function removeEntry($index)
    {
        // For security: supress SQL injection
        settype($index, 'Integer');

        $result = mysql_query("DELETE FROM guestbook WHERE indes = '$index'");

        return $result;
    }
}
?>
